### ISSUE TITLE
Redhat repo does not have stress-ng package

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#1036]
https://snapcraft.io/install/stress-ng/rhel This page does not work in Azure because of below broken step 

This impact many test cases failure.

/# sudo yum install snapd
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Extra Packages for Enterprise Linux Modular 8.2 - x86_64                                   51 kB/s |  67 kB     00:01
Errors during downloading metadata for repository 'epel-modular':
  - Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=epel-modular-8.2&arch=x86_64&infra=$infra&content                                  =$contentdir (IP: xx.xx.xx.xx)
  - Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=epel-modular-8.2&arch=x86_64&infra=$infra&content                                  =$contentdir (IP: xx.xx.xx.xx)
  - Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=epel-modular-8.2&arch=x86_64&infra=$infra&content                                  =$contentdir (IP: xx.xx.xx.xx)
Error: Failed to download metadata for repo 'epel-modular': Cannot prepare internal mirrorlist: Status code: 404 for https                                  ://mirrors.fedoraproject.org/metalink?repo=epel-modular-8.2&arch=x86_64&infra=$infra&content=$contentdir (IP: xx.xx.xx.xx)

**Comment by LiliDeng** [comment]
close old one
