### ISSUE TITLE
pkey fine verification 

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#1041]
PKEY will always be at index 0.

Please add a comment as to what the expected PKEYs are and verify the second PKEY is 0x7fff (this applies to CX3-Pro. Don't recall if it's the same case in CX-5 and newer)
$pkeys = executeRemoteCommand $ipaddress "cat /sys/class/infiniband/mlx4_0/ports/1/pkeys/*"
if (!($pkeys[0] -match "0x8[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]" -and $pkeys[1] -eq "0x7fff"))
{
Write-LogError "Unexpected PKEYs in ${$ipaddress}: $pkeys"
exit 1
}

Need to take care of fine verification later

**Comment by squirrelsc** [comment]
Close old threads.
