### ISSUE TITLE
LISAv2: Introduce SupportedVMSize flag to test cases

### ISSUE THREAD

**Issue by chvalean** [microsoft/lisa#108]
new tag in xml:
	<test>
		<testName>INFINIBAND-INTEL-MPI-2VM</testName>
        <eligibleVMSize>Standard_NC6,Standard_NV24</eligibleVMSize>

This can be overrided by the -CustomParameter flag to lisav2.
Flag can also support wildcard matching - Standard_NV*

First phase to cover: NVME, GPU, DPDK and RDMA.

**Comment by ader1990** [comment]
Closing this, as it will implemented in another way in the future.
