### ISSUE TITLE
Post VM deployment failures are not captured in telemetry database

### ISSUE THREAD

**Issue by iamshital** [microsoft/lisa#117]
**Targetted issues -** 
Azure: 
1. OSProvisioningTimedOut 

**Why this is required?**
When running thousands of tests, it is not possible to go through the console logs to check all the results.
So we rely on power-bi reports / junit captured results. 
But, the trivial error - 'OSProvisioningTimedOut' is not making it's way to Telemetry DB. So this gives a false sense of security.

**Comment by LiliDeng** [comment]
Like https://linuxpipeline.westus2.cloudapp.azure.com/job/pipeline-azure-latest-image/job/master/140/consoleFull, case abort in precheck, also not send to databse.

**Comment by squirrelsc** [comment]
Close old threads.
