### ISSUE TITLE
dependencies should just have a setup script

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#1375]
This is a pet peeve, we should know the dependencies for an OS platform and version, so why don't we just give the user a setup script to install any package manager dependencies? Rather than saying 'here are the dependencies for ubuntu 20.04, copy and paste this from the docs, also if you're on another system have fun ✌️'

**Comment by squirrelsc** [comment]
That's doable, but the cost is higher. We may do it later. The document asks people to read and understand, the script must work as expected. People has different expectations on them.

**Comment by mcgov** [comment]
closing now that we have moved to pip
