### ISSUE TITLE
wait_delete doesn't work

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#1484]
Repro:
Make a lisav3 job, set -v "wait_delete:True" on commandline.
Resource group is still deleted at the end.

**Comment by squirrelsc** [comment]
@mcgov  can you share the runbook you used (be carefully to remove the sensitive information)? Check if the "wait_delete" exists. In the default runbooks, this variable is used to specify if wait the resource group to be deleted or not. It doesn't prevent to delete. If you want to keep an environment after test is done, try "keep_environment:always" with default Azure runbook.
