### ISSUE TITLE
Method for signals other than SIGKILL

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#1485]
Some programs like to be killed with SIGINT rather than SIGKILL, it would be nice to be able to send signals other than kill for some async programs.

**Comment by squirrelsc** [comment]
@mcgov Thank you for suggestions. LISA use below logic to send kill signal. Can you explain more on the suggestions? 

There are several things to be considered. The built-in signal constants depends installed Python package. So the signal.SIGTERM here, may be not what want to run remotely. For example, the local is Windows, the remote is Linux. We cannot send SIGTERM to remote. We have to send the hard coded number "9" to remote.

```python
    def kill(self) -> None:
        if self._process:
            if self._shell.is_remote:
                # Support remote Posix so far
                self._process.send_signal(9)
            else:
                # local process should use the compiled value
                # the value is different between windows and posix
                self._process.send_signal(signal.SIGTERM)
```

**Comment by mcgov** [comment]
The specific instance I ran into was a program where you want to kill it by sending INT instead of KILL. KILL just kills it, INT prints some nice statistics and then kills it. I don't think we need to necessarily use the python signal.<name> definition of the signal number, but having a table of signals for each OS that has different definitions doesn't seem too difficult to manage. My general idea was just that the user should be able to specify INT or KILL or whichever signal somehow and be able to send it to a remote process.

**Comment by squirrelsc** [comment]
The INT may not be handled correctly by the target process, so the kill may not be effective. The KILL makes sure the process is ended immediately. Another idea is to implement a tool call `kill`, it can specify which signal to send, and fit to more scenarios. For kill, a graceful way is to send INT firstly, if it's timeout in one or two seconds, then send KILL. Would you like to create the Kill tool?

**Comment by mcgov** [comment]
That's true, wrapping kill or killall in a tool would fit the use case

**Comment by mcgov** [comment]
I can create those :)

**Comment by mcgov** [comment]
this was implemented in the kill tool, closing
