### ISSUE TITLE
mount tool breaks when using hugetlbfs

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#1505]
A weird issue.
```
       # these lines work
        mount.run("-t hugetlbfs nodev /mnt/huge", sudo=True)
        mount.run("-t hugetlbfs -o 'pagesize=1G' nodev /mnt/huge-1G", sudo=True)
        # these lines break
        # mount.mount("nodev", "/mnt/huge", type="hugetlbfs")
        # mount.mount("nodev", "/mnt/huge-1G", type="hugetlbfs", options="'pagesize=1G'")
```

The bottom two lines fail during node.shell.mkdir with a permissions error. The weird bit is that the top lines don't bother to make the directory first but still succeed.

**Comment by squirrelsc** [comment]
@LiliDeng can you have a look?

**Comment by squirrelsc** [comment]
The command should call `run` as much as possible, instead of `execute`. There are rich logic in `run` of tool, like cache results, auto sudo.

**Comment by LiliDeng** [comment]
I will take a look.
