### ISSUE TITLE
Gpu : is_module_loaded always returns True

### ISSUE THREAD

**Issue by kamalca** [microsoft/lisa#1528]
Having a generator without an `any` or `all` modifier as done in gpy.py : L135 does not produce the desired behavior. In this case, the condition always returns False, meaning that the function will always return True.

My suggested edit:
``` Python 
def is_module_loaded(self) -> bool:
    lsmod_tool = self._node.tools[Lsmod]
    if any (lsmod_tool.module_exists(vendor) for vendor in self.gpu_vendor):
        return True

    return False
```

Defaulting to False is good practice.

**Comment by kamalca** [comment]
@sharsonia I would appreciate your input

**Comment by sharsonia** [comment]
Let me fix this.
