### ISSUE TITLE
(Suspected) Missing `apt update`

### ISSUE THREAD

**Issue by kamalca** [microsoft/lisa#1554]
Using `Posix.install_packages("dracut-core")` fails on Ubuntu 18.04. I believe this is because `apt update` needs to be run before trying to install.

Here is the error:
`2021-09-28 20:26:46.328[19280][INFO] lisa.RootRunner                      HvModule.initrd_modules_check: FAILED   failed. AssertionError: [Failed to install ['dracut-core'], please check the package name and repo are correct or not.
E: Package 'dracut-core' has no installation candidate

get unexpected exit code on cmd ['sudo', 'DEBIAN_FRONTEND=noninteractive', 'apt-get', '-y', 'install', 'dracut-core']] Expected <100> to be equal to <0>, but was not.`

Booting a VM confirms that trying to install `dracut-core` before running `apt update` will cause an error. Therefore I assume that is the problem here.

**Comment by kamalca** [comment]
I see where `apt update` should be running. I confirmed `_initialize_package_installation` is called and runs `apt-get update`. So now I'm not sure what is causing the issue.

**Comment by LiliDeng** [comment]
@kamalca did you meet this 100%?

**Comment by squirrelsc** [comment]
Do you have log file? Check if there is any output form `apt-get update`.

**Comment by kamalca** [comment]
[lisa-20210929-021753-556.log](https://github.com/microsoft/lisa/files/7255391/lisa-20210929-021753-556.log)

It looks like everything is running properly, but the behavior is as if `apt-get update` was never run.

~I am getting this error every time~ *Turns out this error is not occurring consistently.*

**Comment by LiliDeng** [comment]
From the log, it said that 'dracut-core' doesn't exist...

**Comment by mcgov** [comment]
I think I'm hitting this too with dpdk-dev and dpdk from the package manager

**Comment by squirrelsc** [comment]
@mcgov can you share a full log?

**Comment by mcgov** [comment]
Yep will post, I'm seeing a couple of weird errors testing so trying to sort them out.

**Comment by LiliDeng** [comment]
I think this issue was fix in PR #2327 , feel free to reopen it when you still see such issue.
