### ISSUE TITLE
Yum error codes are incorrect, no indication of which package is missing in logs.

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#1613]
at lisa\operating_system.py:973

Code mentions that Yum return 1 on 'already installed' but this isn't true for all versions of yum.
post-dnf yum indicates that 1 is returned when an error occurred that was handled by dnf.

My testing indicates 1 is returned when a package is not available and when it is already installed yum is returning 0 for success.
The issue with long package lists is that if one package is unavailable we don't get an indication of which package was missing in the current scheme. We don't fail on return code 1 so a package missing results in the test still running, even though package installation has failed.

**Comment by squirrelsc** [comment]
Good to know that, we can fix it later. You are welcome to fix it too. :)
