### ISSUE TITLE
Remove hardcode sleeps in kdumpcrash.py

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/lisa#1636]
There is a sleep10 seconds in kdump test case. Replace it to a timeout loop and check some condition. We need to avoid sleep a big number.

**Comment by LiliDeng** [comment]
Fixed in https://github.com/microsoft/lisa/pull/2131/files#diff-48023663bed18c6c5b3e05d824af70a40b40543dfdff0208cff659e5b538fa15L323
