### ISSUE TITLE
LISAv2 summary is missing some aborted tests

### ISSUE THREAD

**Issue by iamshital** [microsoft/lisa#170]
In below logs, Test ID 17 and 18 are missing.

```
[LISAv2 Test Results Summary]
Test Run On           : 04/30/2019 14:43:23
ARM Image Under Test  : Canonical : UbuntuServer : 16.04-LTS : latest
Test Category         : Functional
Test Area             : CORE
Total Test Cases      : 20 (18 Passed, 0 Failed, 2 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:1:4
   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes)
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 TIME-CLOCKEVENT-SMP                                                               PASS                 0.53
    2 CORE                 RELOAD-MODULES-SMP                                                                PASS                11.02
    3 CORE                 LSVMBUS                                                                           PASS                 0.52
    4 CORE                 VERIFY-DEPLOYMENT-PROVISION                                                       PASS                 2.32
        FirstBoot : PASS
        FirstBoot : Call Trace Verification : PASS
        Reboot : PASS
        Reboot : Call Trace Verification : PASS
    5 CORE                 VERIFY-LINUX-CONFIGURATION                                                        PASS                 0.63
    6 CORE                 LIS-MODULES-CHECK                                                                 PASS                 0.64
    7 CORE                 VERIFY-LIS-MODULES-VERSION                                                        PASS                 0.51
    9 CORE                 VERIFY-VHD-PREREQUISITES                                                          PASS                 0.96
   10 CORE                 TIMESYNC-NTP                                                                      PASS                 0.89
   11 CORE                 TIME-CLOCKSOURCE                                                                  PASS                 0.56
   12 CORE                 TIME-CLOCKEVENT-UP                                                                PASS                 0.53
   13 CORE                 INITRD-MODULES-CHECK                                                              PASS                 1.33
   14 CORE                 CPU-VERIFY-ONLINE                                                                 PASS                 0.53
   15 CORE                 TIMESYNC-BASIC                                                                    PASS                 0.89
   16 CORE                 VERIFY-LINUX-DISK-SETUP                                                           PASS                 0.59
        Reboot : Call Trace Verification : PASS
   19 CORE                 VERIFY-DEPLOYMENT-PROVISION-EPHEMERAL-MANAGED-DISK                             Aborted                    0
   20 CORE                 L3-CACHE-CHECK                                                                    PASS                 0.54
```

**Comment by LiliDeng** [comment]
test case abort before summary added, is it not expected?

**Comment by juhlee-microsoft** [comment]
No longer reproduced the issue with CORE.

[Canonical UbuntuServer 16.04-LTS latest] [LISAv2 Test Results Summary]
[Canonical UbuntuServer 16.04-LTS latest] Test Run On           : 12/05/2019 00:19:45
[Canonical UbuntuServer 16.04-LTS latest] ARM Image Under Test  : Canonical : UbuntuServer : 16.04-LTS : latest
[Canonical UbuntuServer 16.04-LTS latest] Test Category         : Functional
[Canonical UbuntuServer 16.04-LTS latest] Test Area             : CORE
[Canonical UbuntuServer 16.04-LTS latest] Initial Kernel Version: 4.15.0-1063-azure
[Canonical UbuntuServer 16.04-LTS latest] Final Kernel Version  : 4.15.0-1063-azure
[Canonical UbuntuServer 16.04-LTS latest] Total Test Cases      : 22 (22 Passed, 0 Failed, 0 Aborted, 0 Skipped)
[Canonical UbuntuServer 16.04-LTS latest] Total Time (dd:hh:mm) : 0:1:16
[Canonical UbuntuServer 16.04-LTS latest] 
[Canonical UbuntuServer 16.04-LTS latest]    ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
[Canonical UbuntuServer 16.04-LTS latest] -------------------------------------------------------------------------------------------------------------------------------------------
[Canonical UbuntuServer 16.04-LTS latest]     1 CORE                 VERIFY-DEPLOYMENT-PROVISION-EPHEMERAL-MANAGED-DISK                                PASS                 1.91 
[Canonical UbuntuServer 16.04-LTS latest] 	FirstBoot : PASS 
[Canonical UbuntuServer 16.04-LTS latest] 	FirstBoot : Call Trace Verification : PASS 
[Canonical UbuntuServer 16.04-LTS latest] 	Reboot : PASS 
[Canonical UbuntuServer 16.04-LTS latest] 	Reboot : Call Trace Verification : PASS 
[Canonical UbuntuServer 16.04-LTS latest]     2 CORE                 VM-HOT-RESIZE                                                                     PASS                  3.7 
[Canonical UbuntuServer 16.04-LTS latest]     3 CORE                 VERIFY-DEPLOYMENT-PROVISION                                                       PASS                 1.89 
[Canonical UbuntuServer 16.04-LTS latest] 	FirstBoot : PASS 
[Canonical UbuntuServer 16.04-LTS latest] 	FirstBoot : Call Trace Verification : PASS 
[Canonical UbuntuServer 16.04-LTS latest] 	Reboot : PASS 
[Canonical UbuntuServer 16.04-LTS latest] 	Reboot : Call Trace Verification : PASS 
[Canonical UbuntuServer 16.04-LTS latest]     4 CORE                 VERIFY-LINUX-CONFIGURATION                                                        PASS                 0.49 
[Canonical UbuntuServer 16.04-LTS latest]     5 CORE                 LIS-MODULES-CHECK                                                                 PASS                  0.5 
[Canonical UbuntuServer 16.04-LTS latest]     6 CORE                 VERIFY-LIS-MODULES-VERSION                                                        PASS                 0.41 
[Canonical UbuntuServer 16.04-LTS latest]     7 CORE                 VERIFY-BOOT-ERROR-WARNINGS                                                        PASS                 0.47 
[Canonical UbuntuServer 16.04-LTS latest]     8 CORE                 VERIFY-VHD-PREREQUISITES                                                          PASS                 0.84 
[Canonical UbuntuServer 16.04-LTS latest]     9 CORE                 TIMESYNC-NTP                                                                      PASS                 1.03 
[Canonical UbuntuServer 16.04-LTS latest]    10 CORE                 TIME-CLOCKSOURCE                                                                  PASS                 0.59 
[Canonical UbuntuServer 16.04-LTS latest]    11 CORE                 TIME-CLOCKEVENT-UP                                                                PASS                 0.41 
[Canonical UbuntuServer 16.04-LTS latest]    12 CORE                 INITRD-MODULES-CHECK                                                              PASS                 1.56 
[Canonical UbuntuServer 16.04-LTS latest]    13 CORE                 VMBUS_VERIFY_HEARTBEAT_PROPERTIES                                                 PASS                 0.58 
[Canonical UbuntuServer 16.04-LTS latest]    14 CORE                 VERIFY-LINUX-DISK-SETUP                                                           PASS                 0.46 
[Canonical UbuntuServer 16.04-LTS latest]    15 CORE                 VMBUS_VERIFY_INTERRUPTS                                                           PASS                 0.72 
[Canonical UbuntuServer 16.04-LTS latest]    16 CORE                 TIME-CLOCKEVENT-SMP                                                               PASS                 0.41 
[Canonical UbuntuServer 16.04-LTS latest]    17 CORE                 RELOAD-MODULES-SMP                                                                PASS                 7.73 
[Canonical UbuntuServer 16.04-LTS latest]    18 CORE                 LSVMBUS                                                                           PASS                 0.79 
[Canonical UbuntuServer 16.04-LTS latest]    19 CORE                 VERIFY-DEPLOYMENT-PROVISION-SRIOV                                                 PASS                  2.4 
[Canonical UbuntuServer 16.04-LTS latest] 	FirstBoot : PASS 
[Canonical UbuntuServer 16.04-LTS latest] 	FirstBoot : Call Trace Verification : PASS 
[Canonical UbuntuServer 16.04-LTS latest] 	Reboot : PASS 
[Canonical UbuntuServer 16.04-LTS latest] 	Reboot : Call Trace Verification : PASS 
[Canonical UbuntuServer 16.04-LTS latest]    20 CORE                 CPU-VERIFY-ONLINE                                                                 PASS                 0.41 
[Canonical UbuntuServer 16.04-LTS latest]    21 CORE                 L3-CACHE-CHECK                                                                    PASS                 0.42 
[Canonical UbuntuServer 16.04-LTS latest]    22 CORE                 PCI-DEVICE-DISABLE-ENABLE-SRIOV-NVME                                              PASS                 0.83 
[Canonical UbuntuServer 16.04-LTS latest] 
[Canonical UbuntuServer 16.04-LTS latest] 
[Canonical UbuntuServer 16.04-LTS latest] Logs can be found at C:\LISAv2\GN86\TestResults\2019-05-12-00-19-41-2305
