### ISSUE TITLE
Reduce function complexity for _prepare_environment function 

### ISSUE THREAD

**Issue by dsrivastavv** [microsoft/lisa#1801]
https://github.com/microsoft/lisa/blob/a874b00e28a7f3935509dd94d440ad937fc84e75/lisa/sut_orchestrator/azure/platform_.py#L305-L311

**Comment by Krytan** [comment]
@somil55 Does help is still needed in this issue? I would like to solve this, It will be my first open source contribution for this repository.

**Comment by LiliDeng** [comment]
Fixed in https://github.com/microsoft/lisa/pull/2220/files#diff-23cef282c9cdd9bba151475396f0470d0775ad931d6f4f40a1c63f5f6165393dR351
