### ISSUE TITLE
Move exit code check to run function

### ISSUE THREAD

**Issue by dsrivastavv** [microsoft/lisa#1804]
Earlier:
https://github.com/microsoft/lisa/blob/236211f7ff36af67ece2d3384b322593df64b64c/lisa/tools/lsmod.py#L38-L48

New format:
https://github.com/microsoft/lisa/blob/8229cc9b89954de6f5407e35a138681fd2ef0118/lisa/tools/modprobe.py#L53-L62

**Comment by snosratiershad** [comment]
@somil55, should this change applied wildly on everywhere we check exit codes?

**Comment by dsrivastavv** [comment]
@snosratiershad yes
