### ISSUE TITLE
Infiniband tests: Fix test failure exit

### ISSUE THREAD

**Issue by chvalean** [microsoft/lisa#194]
RDMA tests are not supported on RHEL8, however the automation will not ack this and exit immediately.
The test will continue to run until getting into timeout.
Logging is correct, but the test execution should end and exit immediately.

If RHEL8 is to be supported, packages must be updated/handled separately, as RHEL8 has many obsolete packages, or different names for some (like python -> python3).

Condition: https://github.com/LIS/LISAv2/blob/master/Testscripts/Linux/SetupRDMA.sh#L63

MPI type   intel does not support on 'redhat_8' or not implement. Test still ran for 123   minutes
MPI type   mvapich does not support on 'redhat_8' or not implement. Test did not   immediately exit, it ran for 124 minutes

**Comment by chvalean** [comment]
@adriansuhov @juhlee-microsoft please ack this and discuss on the required fix and/or support for RDMA on rhel8.
Thank you!

**Comment by LiliDeng** [comment]
#465

**Comment by LiliDeng** [comment]
@chvalean #465 fix this?

**Comment by LiliDeng** [comment]
@chvalean Let know any further work need do for this issue, thanks!
