### ISSUE TITLE
DPDK: skip TC VERIFY-OVS-DPDK on non debian platforms

### ISSUE THREAD

**Issue by ader1990** [microsoft/lisa#200]
VERIFY-OVS-DPDK supports only DEBIAN based platforms for the moment, so it makes sense to skip the test on the other platforms.

**Comment by LiliDeng** [comment]
Is any way to skip them against upstream kernel?

**Comment by chvalean** [comment]
> Is any way to skip them against upstream kernel?

This should be handled by excluding the dpdk tests in the upstream pipeline in my opinion.

**Comment by LiliDeng** [comment]
Thanks Chris for your reply! Yes, that's what I did currently.
