### ISSUE TITLE
Azure Gen2 VM support

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#203]
In the API this is referenced by the HyperVGenerationType property, as defined here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/compute.json#L4690

**Comment by LiliDeng** [comment]
any link to introduce the azure gen2 VM?

**Comment by chvalean** [comment]
> any link to introduce the azure gen2 VM?

I updated the description.

**Comment by LiliDeng** [comment]
> any link to introduce the azure gen2 VM?
> 
> I updated the description.

Thanks @chvalean , if we specify gen2 , then azure deploy gen2 VM, then start testing, otherwise keep current behavior?

**Comment by chvalean** [comment]
Right, it should follow the same pattern as for Hyper-V vm generation parameter that exists in lisav2:
- if vmgeneration param is not specified at all (or explicitly given as gen1), default to gen1.
- if "vmgeneration 2" is specified, go with that.

**Comment by iamshital** [comment]
> Right, it should follow the same pattern as for Hyper-V vm generation parameter that exists in lisav2:
> 
> * if vmgeneration param is not specified at all (or explicitly given as gen1), default to gen1.
> * if "vmgeneration 2" is specified, go with that.

@chvalean @LiliDeng , Azure will deploy Gen2 VM if the VM size is designated to Gen2. I don't think that, we can control this behavior through LISAv2.

**Comment by juhlee-microsoft** [comment]
Azure market gallery image got updated as "GEN2: SUSE Linux Enterprise Server (SLES) 12 SP4 for SAP Applications", for example. So Penguinator or other pipeline can pick up the Gen2 image in run-time. However, we would put the information label in pipeline page 'If you choose Gen2 image above, you would select suport VM size in 'OverrideVMSize' field.
