### ISSUE TITLE
node.os needs a method to check available package versions before install

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#2052]
Currently we can install packages and check their version after installation. It would be better if there was a function exposing apt search and similar options to check the upstream version before installation.

options: 
- change package_exists to return a VersionInfo instead of a bool, I'm not sure if this will break the current usage, maybe Union[VersionInfo|None] would work
- add a check_available_package_version function to fetch and parse version info from the package manager.

**Comment by squirrelsc** [comment]
There is a method to check if a package available or not. Maybe we can return versions together.
