### ISSUE TITLE
Handle obsolete packages in RHEL 8.x

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#212]
obsolete packages - rhel8 has a long list of obsolete packages, automation is failing due to not finding them (We found this in 8.0 GA testing, and fix in the package update call)

**Comment by juhlee-microsoft** [comment]
Nested  - 

missing packages in rhel8 - bridge-utils. Missing epel for rhel8 - required for qemu-system-x86
--

**Comment by LiliDeng** [comment]
#248 is not fix for this issue.

**Comment by xian123** [comment]
Missing epel for rhel8: There is no EPEL repository published to support it yet. On the [Fedora wiki](https://fedoraproject.org/wiki/Infrastructure_2020/EPEL-8) page the beta date is marked as 2019.07.01.This may or may not change.

**Comment by chvalean** [comment]
Right, he should wait for epel and see if some packages might be available there.
Put this as low priority until epel gets released for rhel8.

**Comment by LiliDeng** [comment]
#623 In RHEL 8, use qemu-kvm
