### ISSUE TITLE
Feature Request: ADO Work Item notifier

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#2157]
Our production tests (hotpatch/evt) should have 100% clean runs, however while we're rolling them out there are lots of small issues we need triaged. It is not efficient to create work items for each of these bugs and this will result in us having buggy test runs as long as this notifier is not created.

Feature ask:
A notifier to create an ADO work item for each failure in a given run. 
- Tag the item with enough info that they are easily sortable (test area, guest OS, vmsize, host build)
- Assign the work item to the test owner (or team in general and allow them to be triaged).
- Add a basic description and repro steps (generate a runbook or commandline?) to the work item.

**Comment by squirrelsc** [comment]
@mcgov Can you move this request to internally? The ADO integration is not public, because if we don't have bandwidth to do it. It doesn't need a notifier. We will add it in case management portal.
