### ISSUE TITLE
[P0] Revert to Managed Disk for Gen2 VM provision

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#222]
[Azure VERIFY-DEPLOYMENT-PROVISION eastus] 5:17:37 PM - Resource Microsoft.Compute/virtualMachines 'LISAv2-OneVM-microsoft-BY76-20190516171703-role-0' failed with message '{
[Azure VERIFY-DEPLOYMENT-PROVISION eastus]   "error": {
[Azure VERIFY-DEPLOYMENT-PROVISION eastus]     "code": "BadRequest",
[Azure VERIFY-DEPLOYMENT-PROVISION eastus]     "### message": "Generation 2 Hypervisor Image and VM Size can only be used with managed-disk VMs."
[Azure VERIFY-DEPLOYMENT-PROVISION eastus]   }
[Azure VERIFY-DEPLOYMENT-PROVISION eastus] }'VERBOSE: 5:17:37 PM - Resource Microsoft.Network/networkInterfaces

**Comment by chvalean** [comment]
This comes from Azure cannot be controlled, it is user driven.
I mean the user must be aware of his deployment options, and not the framework job to work-around a bad input.
Thinking that in the case of custom vhd to create Mv2 in Azure, having any form of correction would be even more complicated.
