### ISSUE TITLE
Linux kernel headers deb fails to install on Ubuntu 19.04

### ISSUE THREAD

**Issue by ader1990** [microsoft/lisa#226]
It seems there is a libssl dependency issue:

dpkg: dependency problems prevent configuration of linux-headers-4.19.24-c52ea7b07f93:
 linux-headers-4.19.24-c52ea7b07f93 depends on libssl1.0.0 (>= 1.0.0); however:
  Package libssl1.0.0 is not installed.

On Ubuntu 19.04. libssl 1.1 is installed.

**Comment by chvalean** [comment]
I've asked @stefanlupsa to research this and decide if this requires a build vm upgrade from current 16.04 ubuntu, or see what other solution is available.

**Comment by stefanlupsa** [comment]
I could repro the issue and tried a potential fix but this does not solve the problem:

If the kernel builder is on xenial the header install will fail on distros that have libssl1.1 as xenial has libssl1.0 and no release candidate for libssl1.1

I tried adding the libssl1.1 from a bionic repo to the xenial kernel builder, this fixes the problem on disco but creates the same problem when installing kernel headers on xenial (and probably on any other distro that has libssl1.0 or less).

**Comment by juhlee-microsoft** [comment]
Resolved in https://github.com/dbcli/mssql-cli/issues/252
