### ISSUE TITLE
Fix ip.restart_device issue with default route

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#2283]
There's a snippet in lisa\tools\ip.py that is used to restart an interface in a few tests, however when called on eth0 (or whichever interface is servicing the ssh connection) it can result in the connection being lost before the command finishes. Interactively this would get called with nohup sh -c "sequence"  to make sure the command sequence can complete even if the ssh connection is dropped.

```
 def restart_device(self, nic_name: str) -> None:
        self.node.execute(
            (
                f"ip link set dev {nic_name} down;ip link set dev {nic_name} up;"
                "dhclient -r;dhclient"
            ),
            shell=True,
            sudo=True,
            expected_exit_code=0,
            expected_exit_code_failure_message=(
                f"fail to restart [down then up] the nic {nic_name}"
            ),
        )

```

**Comment by squirrelsc** [comment]
It looks an easy change. Can you make it happen?

**Comment by LiliDeng** [comment]
Fixed in https://github.com/microsoft/lisa/commit/0f616568f275ba1886bf1fe179b93c45aab24657#diff-e4aac904a5bfbe9441ee74995954d0f27a48ada2666bb2f97604d1766d6c558aR92
