### ISSUE TITLE
& operator in ACC test

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#2291]
https://github.com/microsoft/lisa/blob/11e56c922ce510d5c66f0b76c3156944cd18a59e/microsoft/testsuites/acc/bvt.py#L46

I noticed a line that I think might be a bug, @shruti25ratnam did you mean to use the bitwise operator here? I suspect this should be 'and'. similar line right below it

**Comment by mcgov** [comment]
@LiliDeng no response from the author, does this look right to you?

**Comment by avylove** [comment]
Looks like a no-op bug, since `bool & bool` ends up being the same as `bool and bool`, but I suspect it's slower since with `and` the interpreter won't evaluate the right side if the left side is `False`. The wouldn't be the case with `&`.

**Comment by mcgov** [comment]
Sounds good, we can leave this as low-priority since it's essentially a style fix.

**Comment by avylove** [comment]
I wouldn't say style, it's definitely incorrect.

**Comment by mcgov** [comment]
fixed
