### ISSUE TITLE
Use of 'get_lower_nics' doesn't check if list is empty.

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#2308]
https://github.com/microsoft/lisa/blob/1eb96ce90a62737b935dadee2677dbf9120f0181/microsoft/testsuites/performance/common.py#L262

There are a couple of uses in this file that can result in a list-out-of-range exception if the list is empty. These need to be wrapped and caught since they are an error condition, the test is expecting an SRIOV lower interface and none is present.

**Comment by LiliDeng** [comment]
handled in https://github.com/microsoft/lisa/blob/main/lisa/nic.py#L236C11-L236C11 now
