### ISSUE TITLE
VM-HOT-RESIZE: refine list of tested VM sizes

### ISSUE THREAD

**Issue by chvalean** [microsoft/lisa#258]
Current test takes over 3 hours and goes through 48 VM sizes.

@adriansuhov suggestion to improve this is to take only the smallest and largest VM size from each SKU family.

For example, current code goes through each of these: "“Standard_A0 Standard_A1 Standard_A2 Standard_A3 Standard_A5 Standard_A4 Standard_A6 Standard_A7”"

With the changes, it will deploy only A0 and A7 from the A series.

@xian123  as the original test case owner, can you please work on this?

**Comment by xian123** [comment]
I'm working on it.
