### ISSUE TITLE
Timesync.py does not test the fixing of time drift

### ISSUE THREAD

**Issue by SeanDougherty** [microsoft/lisa#2715]
# What
A test should be added to [timesync.py](https://github.com/microsoft/lisa/blob/ae6f8998fafc4b8c8b746ad67f1c5f7d9f11acf9/microsoft/testsuites/core/timesync.py) that validates that the image can properly rectify the time when it is set to incorrect dates (e.g. via `date --set "27 Feb 2021"`).

# Why
Time drift is handled by chronyd. According to the [Time sync for Linux VMs in Azure](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/time-sync) documentation, chronyd.conf should have its makestep values set to `1.0 -1` to ensure that time drift is always rectified by the chronyd service.

### More details
For more context, see CBLMariner's PR here: https://github.com/microsoft/CBL-Mariner/pull/5314

**Comment by dsrivastavv** [comment]
Added in #2723

**Comment by LiliDeng** [comment]
@SeanDougherty could you please check the new added case by @somil55 in #2723
