### ISSUE TITLE
SRIOV-VERIFY-MAX-VF-CONNECTION-MAX-VCPU: stabilize test-case

### ISSUE THREAD

**Issue by chvalean** [microsoft/lisa#272]
Sometimes, the test will fail at least in Azure with the below.
On retry or manual check of the interfaces, all are present, so it's probably a bad timing in script execution.

```
05/28/2019 11:55:38 : [INFO ] TEST SCRIPT SUMMARY ~~~~~~~~~~~~~~~
Expected VF count: 8. Actual VF count: 8
Successfully sent file from VM1 to VM2 through eth0
Successfully sent file from VM1 to VM2 through eth1
Successfully sent file from VM1 to VM2 through eth2
Successfully sent file from VM1 to VM2 through eth3
Successfully sent file from VM1 to VM2 through eth4
Successfully sent file from VM1 to VM2 through eth5
Successfully sent file from VM1 to VM2 through eth6
Unable to ping 10.0.0.5 through eth7
```

**Comment by LiliDeng** [comment]
SRIOV-VERIFY-MAX-VF-CONNECTION RedHat RHEL 7-RAW 7.6.2019060521
Expected VF count: 8. Actual VF count: 8
Successfully sent file from VM1 to VM2 through eth0
Successfully sent file from VM1 to VM2 through eth1
Unable to ping 10.0.0.5 through eth2
