### ISSUE TITLE
LISA failed to install GPU driver for Azure HPC VM image

### ISSUE THREAD

**Issue by hcoona** [microsoft/lisa#2822]
The Azure HPC image already installed GPU & IB (InfiniBand) driver. ref: https://techcommunity.microsoft.com/t5/azure-compute-blog/azure-hpc-vm-images/ba-p/977094

Shall we detect if the driver is already there and skip the installation?

![logs](https://github.com/microsoft/lisa/assets/712433/1ee28c69-ac88-4a52-b976-2dc7dceda2e6)

**Comment by hcoona** [comment]
I believe the same issue also applies to IB driver.

**Comment by hcoona** [comment]
I think it more reliable if the VM image can provide the drivers. Environment setup is a difficult problem. It would benefit if we decouple it from LISA core functionalities.

1. Make LISA simple and easy.
2. It's hard to make it correctly. We need to detect the environment to judge which version to apply. However, we don't know if many components with vary versions together works fine or not. For example, GPU + IB + PyTorch + ...
3. The maintaining burden is heavy because we need to watch and decide if we need to install a newer version of some component.

**Comment by LiliDeng** [comment]
Fix in #2836
