### ISSUE TITLE
Azure retry deploy if the deployment fails

### ISSUE THREAD

**Issue by ader1990** [microsoft/lisa#283]
Add a configurable retry number for deployments, as when deploying bug vm sizes, it might fail with error 'The vm did not start in the alloted time'

**Comment by LiliDeng** [comment]
maybe it is a distro issue?

**Comment by ader1990** [comment]
If it is a distro issue, that can be caught by special TCs ran multiple times. If I want to run DPDK test cases, I would like to test the DPDK install and not have failures because Azure or the distro itself has provisioning issues X% of the time.

**Comment by ader1990** [comment]
@LiliDeng there is also another reason why LISAv2 might fail to deploy a VM which is not handled in the current code and cannot be - race condition on resource starvation.

Let's consider the following scenario:

One LISAv2 run has one test case to be run which requires to deploy 3 big VMs (total of 90 cores) on Azure. It checks for the subscription if it has the CPU family and quota available and it finds there are 200 cores available, so it goes to create the deployment via ARM. A deployment via ARM is a transaction, which means all the 3 VMs need to be deployed in order for the deploy to be successful. 

At the same time, another LISAv2 run is started which has to deploy on Azure 3 VMs with 150 cores in total, same CPU family. Let s say the first LISAv2 has already started but deployed only 1 VM at that moment, so there are 200 - 30 = 170 cores available, and LISAv2 proceeds with the second deployment.

Depending on the Azure deployment speeds of each deployment (200 < 150 + 90) , the end result will be that one of the deployment will fail, or ever both will fail with the message:

```
Azure deployment failure Error Code=InvalidTemplateDeployment; Message=The template deployment
'x' is not valid. Code=QuotaExceeded; Message=Operation results in exceeding quota limits of standardDSv2Family Cores.
```

**Comment by chvalean** [comment]
Closing this, it is a user responsibility to ensure enough quota is present for the tests to run, or increase the quota based on the requirements.
