### ISSUE TITLE
RELOAD-MODULES-SMP 

### ISSUE THREAD

**Issue by LiliDeng** [microsoft/lisa#292]
Failed against Canonical UbuntuServer 16.04-LTS 16.04.201905303, even the ip is still there, we can't reconnect using ssh, but can ssh if run dhclient -r and dhclient

**Comment by LiliDeng** [comment]
one more issue - no bc tool on this image

**Comment by chvalean** [comment]
Created a TFS task for this, @adriansuhov  will work on it this month.

**Comment by LiliDeng** [comment]
@chvalean Please close TFS task, thanks!
