### ISSUE TITLE
[Log] typo in log

### ISSUE THREAD

**Issue by hcoona** [microsoft/lisa#2949]
There's a typo in log: tocount -> to count

![图片](https://github.com/microsoft/lisa/assets/712433/9972adee-d11c-4165-bcec-1ca6a29421f3)

And I ask to improve the log. It's not a case missing `nvidia-smi`.

**Comment by LiliDeng** [comment]
@hcoona welcome to contribute on lisa.

**Comment by LiliDeng** [comment]
@adityagesh could you please fix this issue, thanks!
