### ISSUE TITLE
current URL for LIS_CURRENT_URL and LIS_OLD_URL is 404

### ISSUE THREAD

**Issue by LiliDeng** [microsoft/lisa#297]

**Comment by chvalean** [comment]
LIS_CURRENT_URL should be pointed to aka.ms/lis
That will give the latest released LIS version.

**Comment by LiliDeng** [comment]
Close this issue, below URLS are valid now.
https://github.com/LIS/LISAv2/blob/master/XML/Other/ReplaceableTestParameters.xml#L400 and https://github.com/LIS/LISAv2/blob/master/XML/Other/ReplaceableTestParameters.xml#L405
