### ISSUE TITLE
CustomKernelInstall: handle unexpected kernel upgrade in Ubuntu

### ISSUE THREAD

**Issue by ader1990** [microsoft/lisa#311]
The removal of linux-cloud-tools-common on Ubuntu 16.04 does also upgrade the kernel, if there is newer kernel available. We need to handle this unexpected behaviour, otherwise a custom kernel install will fail if the upgraded kernel is the same as the custom kernel from the debian files which we want to install.

https://github.com/LIS/LISAv2/blob/master/Testscripts/Linux/customKernelInstall.sh#L302

**Comment by chvalean** [comment]
Ping'd Joe to see if he has any suggestions.

Can use this image ID to repro issue:
Canonical UbuntuServer 16.04-LTS 16.04.201905303
