### ISSUE TITLE
SR-IOV: Add support for CoreOS

### ISSUE THREAD

**Issue by LiliDeng** [microsoft/lisa#331]
OS Version not supported in InstallDependencies!

**Comment by chvalean** [comment]
Better rename to SR-IOV: Add support for CoreOS?
That distro was not on the list of supported distros when implemented, so probably all code will have to be checked.

**Comment by LiliDeng** [comment]
@chvalean Thanks, update

**Comment by LiliDeng** [comment]
Work in progress. affected case SRIOV-INTERRUPTS-CHANGE
