### ISSUE TITLE
DPDK: skip run on SLES 12

### ISSUE THREAD

**Issue by ader1990** [microsoft/lisa#347]
Skip DPDK tests on SLES 12, as according to https://docs.microsoft.com/en-us/azure/virtual-network/setup-dpdk, only SLES 15 is supported.

**Comment by LiliDeng** [comment]
Image: "SUSE SLES 12-SP4 2019.06.17"
VERIFY-DPDK-COMPLIANCE ：PASS 
VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC: ABORTED for reason #305
