### ISSUE TITLE
Remove Update Dependencies CI workflow

### ISSUE THREAD

**Issue by avylove** [microsoft/lisa#3482]
It was made clear in https://github.com/microsoft/lisa/issues/2782 and the closing of it without action, that this project is in a death spiral, but if you're not going to update your dependencies, please remove https://github.com/microsoft/lisa/blob/main/.github/workflows/update_deps.yml so I stop getting notified about it's failures.

**Comment by squirrelsc** [comment]
@LiliDeng please help stop the runs.
