### ISSUE TITLE
GPU: skip run on SLES

### ISSUE THREAD

**Issue by stefanlupsa** [microsoft/lisa#349]
SLES is not spported for NVIDIA GPU drivers on N-series VM

Ref: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/n-series-driver-setup

**Comment by LiliDeng** [comment]
From [here]( http://developer.download.nvidia.com/compute/cuda/repos/), there is cuda package for sles, not sure why can't work on azure, I ever tried, also failed, need further investigation here.

**Comment by chvalean** [comment]
> From [here](http://developer.download.nvidia.com/compute/cuda/repos/), there is cuda package for sles, not sure why can't work on azure, I ever tried, also failed, need further investigation here.

@LiliDeng Please start an internal thread with Josh to clarify if the docs.microsoft documentation is up-to-date, because if so then it remains as Stefan noted, that no gpu testing on sles is to be done.

**Comment by LiliDeng** [comment]
Double confirm with PM.

**Comment by juhlee-microsoft** [comment]
GPU CUDA driver test shall skip if the Guest OS is RHEL 8.x or SUSE. No driver available.

**Comment by LiliDeng** [comment]
Working on it.
