### ISSUE TITLE
CustomLIS: Add support to install from aka.ms/lis

### ISSUE THREAD

**Issue by iamshital** [microsoft/lisa#365]
Current -CustomLIS option only supports -
1. lisnext
2. tar.gz downloadable url.

We need to add support for downloading from aka.ms/lis link and install it.

**Comment by iamshital** [comment]
Assigning to @sireeshapotnuru

**Comment by chvalean** [comment]
maybe have -CustomLIS "latest" which would map to aka.ms link?

**Comment by iamshital** [comment]
> maybe have -CustomLIS "latest" which would map to aka.ms link?

Yes. Sounds good.
