### ISSUE TITLE
All EXT4 tests passed but test case aborted

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#380]
https://github.com/LIS/LISAv2/blob/master/Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1#L88

All EXT4 tests got passed, but because the timer sees the run-time issue, this test got aborted. if all tests passed, then it should be 'passed' not 'aborted'

**Comment by chvalean** [comment]
@adriansuhov  please ack or comment

**Comment by LiliDeng** [comment]
@juhlee-microsoft could you please let know which image you using, is it because the tests hung in ext4/023 cause timeout?

**Comment by juhlee-microsoft** [comment]
I don't recall it was from Mv2 or test kernel testing. I will close this.
