### ISSUE TITLE
Need to upgrade kexec tool to v2.0.15

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#391]
Latest version tool kexec install from trusty repo is 2.0.6, KDUMP cases failed for existed bug 1713940 which fix in version 2.0.15.

Target test case: KDUMP test category
--

**Comment by juhlee-microsoft** [comment]
Verify with default kernel and linuxnext in Trusty, Xenial, Bionic, Cosmic andf Disco.

**Comment by juhlee-microsoft** [comment]
Also there is a known issue of this test failure; emergency mode and hung during reboot. if this is detected, should we print out the bug information in the log?

**Comment by chvalean** [comment]
ubuntu 14.04 does not have a newer kexec-tools version.
We also cannot skip the test, as that version might still work with kdump and other kernels.

**Comment by juhlee-microsoft** [comment]
Any suggestion?

**Comment by chvalean** [comment]
> Any suggestion?

@LiliDeng has some code in PR that will compile kexec-tools from sources.
I would suggest to do that strictly for ubuntu_14.04 (and in the future extend it where needed), otherwise go with whatever the distro provides.

**Comment by juhlee-microsoft** [comment]
@LiliDeng please add comment in the PR
