### ISSUE TITLE
Upgrade util-linux to v2.23 for blkdiscard

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#392]
The util-linux version is 2.20.1-5.1ubuntu20.9 in Trusty, which no command blkdiscard, upgrade it from util-linux-v2.23 which contains blkdiscard.

Target tests: NVME-FSTRIM, NVME-BLKDISCARD, SRIOV-VERIFY-LSPCI

Verify in Trusty with default kernne land linuxnext.

**Comment by chvalean** [comment]
@juhlee-microsoft if I recall, those messages are from trusty only.

trusty is EOL, why update automation with something that we should no longer support?

**Comment by chvalean** [comment]
Verified this, and there is no new util-linux package for trusty 14.04.
Created a PR that will skip NVME-BLKDISCARD on it, I don't see a dependency on the other mentioned tests.
