### ISSUE TITLE
Need to revise NVMe functions

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#394]
Target test: NVME-DISK-VALIDATION
Issue: no need install gcc-c++ kernel-devel, lack of make package in function install_nvme_cli

Target test: NVME-FSTRIM
No need install gcc-c++ kernel-devel, lack of make package in function install_nvme_cli, lack of package xfsprogs for mount xfs system

Target test: NVME-BLKDISCARD
no need install gcc-c++ kernel-devel, lack of make package in function install_nvme_cli, lack of xfsprogs in Format_Mount_NVME

Verify fixes in Trusty, Disco and Bionic of Cannonical with default/linuxnext kernel.

**Comment by chvalean** [comment]
@juhlee-microsoft  if I recall, those messages are from trusty only.

trusty is EOL, why update automation with something that we should no longer support?

**Comment by juhlee-microsoft** [comment]
I am not sure if I saw any EOL declaration yet. We also have new kernel arrival. Let me check out its EOL schedule

**Comment by LiliDeng** [comment]
Code is ready, if needed, I will send out PR.

**Comment by juhlee-microsoft** [comment]
Please do. We will support Trusty, as I forwarded the email to you.

**Comment by chvalean** [comment]
@LiliDeng  please exclude changes to NVME-BLKDISCARD.
I created a separate PR #405 to address that

**Comment by LiliDeng** [comment]
@chvalean Sorry I miss your message here.
