### ISSUE TITLE
Need to update error/warn xml file

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#395]
Found new lines in Trusty kernel below.

lisa@LISAv2-OneVM-trusty-BA58-20190702224809-role-0:~$ more VERIFY-BOOT-ERROR-WARNINGS_summary.log
07/02/2019 10:50:17 PM : INFO : Checking for ERROR and WARNING messages in system logs.
07/02/2019 10:50:17 PM : DEBUG : 551:Jun 29 06:38:21 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 HV_FCOPY: open /dev/vmbus/hv_fcopy failed; error: 2 No such file or directory
1220:Jun 29 06:41:59 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 HV_FCOPY: open /dev/vmbus/hv_fcopy failed; error: 2 No such file or directory
1764:Jul  2 22:49:13 LISAv2-OneVM-trusty-BA58-20190702224809-role-0 HV_FCOPY: open /dev/vmbus/hv_fcopy failed; error: 2 No such file or directory

07/02/2019 10:50:17 PM : DEBUG : 2:Jun 29 06:38:20 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 rsyslogd-2307: warning: ~ action is deprecated, consider using the 'stop' statement instead [try http://www.rsyslog.com/e/2307 ]
578:Jun 29 06:38:36 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 logger: Added ephemeral disk warning to /mnt/DATALOSS_WARNING_README.txt
579:Jun 29 06:38:36 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 logger: WARNING: /mnt is an ephemeral disk. See /mnt/DATALOSS_WARNING_README.txt for more information
690:Jun 29 06:41:59 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 rsyslogd-2307: warning: ~ action is deprecated, consider using the 'stop' statement instead [try http://www.rsyslog.com/e/2307 ]
1246:Jun 29 06:42:30 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 logger: WARNING: /mnt is an ephemeral disk. See /mnt/DATALOSS_WARNING_README.txt for more information
1252:Jul  2 22:49:12 LISAv2-OneVM-trusty-BA58-20190702224809-role-0 rsyslogd-2307: warning: ~ action is deprecated, consider using the 'stop' statement instead [try http://www.rsyslog.com/e/2307 ]
1781:Jul  2 22:49:34 LISAv2-OneVM-trusty-BA58-20190702224809-role-0 kernel: [   34.304076] random: 1 urandom warning(s) missed due to ratelimiting
1797:Jul  2 22:50:04 LISAv2-OneVM-trusty-BA58-20190702224809-role-0 logger: Added ephemeral disk warning to /mnt/DATALOSS_WARNING_README.txt
1798:Jul  2 22:50:04 LISAv2-OneVM-trusty-BA58-20190702224809-role-0 logger: WARNING: /mnt is an ephemeral disk. See /mnt/DATALOSS_WARNING_README.txt for more information

07/02/2019 10:50:17 PM : DEBUG : 264:Jun 29 06:38:20 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 kernel: [    0.544008] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
956:Jun 29 06:41:59 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 kernel: [    0.444010] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
1494:Jul  2 22:49:12 LISAv2-OneVM-trusty-BA58-20190702224809-role-0 kernel: [    0.376012] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.

07/02/2019 10:50:17 PM : INFO : Checking ignorable boot ERROR/WARNING/FAILURE messages...
07/02/2019 10:50:17 PM : INFO : Ignorable ERROR/WARNING/FAILURE message: 264:Jun 29 06:38:20 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 kernel: [    0.544008] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
07/02/2019 10:50:17 PM : INFO : Ignorable ERROR/WARNING/FAILURE message: 956:Jun 29 06:41:59 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 kernel: [    0.444010] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
07/02/2019 10:50:17 PM : INFO : Ignorable ERROR/WARNING/FAILURE message: 1494:Jul  2 22:49:12 LISAv2-OneVM-trusty-BA58-20190702224809-role-0 kernel: [    0.376012] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
07/02/2019 10:50:17 PM : INFO : Ignorable ERROR/WARNING/FAILURE message: 551:Jun 29 06:38:21 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 HV_FCOPY: open /dev/vmbus/hv_fcopy failed; error: 2 No such file or directory
07/02/2019 10:50:17 PM : INFO : Ignorable ERROR/WARNING/FAILURE message: 1220:Jun 29 06:41:59 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 HV_FCOPY: open /dev/vmbus/hv_fcopy failed; error: 2 No such file or directory
07/02/2019 10:50:17 PM : INFO : Ignorable ERROR/WARNING/FAILURE message: 1764:Jul  2 22:49:13 LISAv2-OneVM-trusty-BA58-20190702224809-role-0 HV_FCOPY: open /dev/vmbus/hv_fcopy failed; error: 2 No such file or directory
07/02/2019 10:50:17 PM : INFO : Ignorable ERROR/WARNING/FAILURE message: 578:Jun 29 06:38:36 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 logger: Added ephemeral disk warning to /mnt/DATALOSS_WARNING_README.txt
07/02/2019 10:50:17 PM : INFO : Ignorable ERROR/WARNING/FAILURE message: 1781:Jul  2 22:49:34 LISAv2-OneVM-trusty-BA58-20190702224809-role-0 kernel: [   34.304076] random: 1 urandom warning(s) missed due to ratelimiting
07/02/2019 10:50:17 PM : INFO : Ignorable ERROR/WARNING/FAILURE message: 1797:Jul  2 22:50:04 LISAv2-OneVM-trusty-BA58-20190702224809-role-0 logger: Added ephemeral disk warning to /mnt/DATALOSS_WARNING_README.txt
07/02/2019 10:50:17 PM : ERROR : Found ERROR/WARNING/FAILURE messages in logs.
07/02/2019 10:50:17 PM : INFO : warnings: 2:Jun 29 06:38:20 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 rsyslogd-2307: warning: ~ action is deprecated, consider using the 'stop' statement instead [try http://www.rsyslog.com/e/2307 ]
07/02/2019 10:50:17 PM : INFO : warnings: 579:Jun 29 06:38:36 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 logger: WARNING: /mnt is an ephemeral disk. See /mnt/DATALOSS_WARNING_README.txt for more information
07/02/2019 10:50:17 PM : INFO : warnings: 690:Jun 29 06:41:59 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 rsyslogd-2307: warning: ~ action is deprecated, consider using the 'stop' statement instead [try http://www.rsyslog.com/e/2307 ]
07/02/2019 10:50:17 PM : INFO : warnings: 1246:Jun 29 06:42:30 LISAv2-OneVM-lilitest-LW14-20190628233613-role-0 logger: WARNING: /mnt is an ephemeral disk. See /mnt/DATALOSS_WARNING_README.txt for more information
07/02/2019 10:50:17 PM : INFO : warnings: 1252:Jul  2 22:49:12 LISAv2-OneVM-trusty-BA58-20190702224809-role-0 rsyslogd-2307: warning: ~ action is deprecated, consider using the 'stop' statement instead [try http://www.rsyslog.com/e/2307 ]
07/02/2019 10:50:17 PM : INFO : warnings: 1798:Jul  2 22:50:04 LISAv2-OneVM-trusty-BA58-20190702224809-role-0 logger: WARNING: /mnt is an ephemeral disk. See /mnt/DATALOSS_WARNING_README.txt for more information
lisa@LISAv2-OneVM-trusty-BA58-20190702224809-role-0:~$

Target test: VERIFY-BOOT-ERROR-WARNINGS
Verify fix in Trusty, Bionic and Disco kernel in Ubuntu.

**Comment by juhlee-microsoft** [comment]
This is for Xenial.

07/01/2019 06:23:50 PM : ERROR : Found ERROR/WARNING/FAILURE messages in logs.
07/01/2019 06:23:50 PM : INFO : warnings: 1296:Jun 29 06:57:47 LISAv2-OneVM-lilitest-OU49-20190628235329-role-0 hv_fcopy_daemon[10869]: WARNING: hv_fcopy_daemon not found for kernel 4.15.0-1049
07/01/2019 06:23:50 PM : INFO : warnings: 1306:Jun 29 06:57:47 LISAv2-OneVM-lilitest-OU49-20190628235329-role-0 hv_kvp_daemon[10886]: WARNING: hv_kvp_daemon not found for kernel 4.15.0-1049
07/01/2019 06:23:50 PM : INFO : warnings: 1316:Jun 29 06:57:47 LISAv2-OneVM-lilitest-OU49-20190628235329-role-0 hv_vss_daemon[10903]: WARNING: hv_vss_daemon not found for kernel 4.15.0-1049

****

**Comment by juhlee-microsoft** [comment]
This is for Bionic.

07/01/2019 06:20:43 PM : ERROR : Found ERROR/WARNING/FAILURE messages in logs.
07/01/2019 06:20:43 PM : INFO : warnings: 1465:Jun 29 07:13:35 LISAv2-OneVM-lilitest-YL88-20190629000811-role-0 hv_fcopy_daemon[11400]: WARNING: hv_fcopy_daemon not found for kernel 4.18.0-1023
07/01/2019 06:20:43 PM : INFO : warnings: 1474:Jun 29 07:13:35 LISAv2-OneVM-lilitest-YL88-20190629000811-role-0 hv_kvp_daemon[11401]: WARNING: hv_kvp_daemon not found for kernel 4.18.0-1023
07/01/2019 06:20:43 PM : INFO : warnings: 1483:Jun 29 07:13:35 LISAv2-OneVM-lilitest-YL88-20190629000811-role-0 hv_vss_daemon[11404]: WARNING: hv_vss_daemon not found for kernel 4.18.0-1023

**Comment by chvalean** [comment]
@juhlee-microsoft @LiliDeng the discussion that needs to happen for test VERIFY-BOOT-ERROR-WARNINGS is how to redesign it.

Currently it will get all boot log and compare warnings/errors against an ignore list.

This is clearly producing too much noise, as the messages are usually comming from all system components, which don't relate to LIS nor are relevant to us.

One idea would be just to filter out messages from hv/hyperv/wala. And maybe still keep the ignore list for messages that we know are not relevant in Azure, like the ones from fcopy.

That would make the test more stable and relevant, instead of just going through messages that are not relevant to the functionality we're after.

**Comment by squirrelsc** [comment]
Close old threads.
