### ISSUE TITLE
NVIDIA-CUDA-DRIVER-TENSORFLOW abort on U16.04 + proposed-azure and proposed-edge

### ISSUE THREAD

**Issue by LiliDeng** [microsoft/lisa#409]
Test case abort when run tensorflow against ubuntu 16.04 + proposed-azure/proposed-edge kernel.
When run python tf_cnn_benchmarks.py with batch_size 512 hit memory issue.

**Comment by juhlee-microsoft** [comment]
It needs to isolate/characterize the problem in details, but if this is simply occurring with new kernel, I believe Canonical should be interested. Please add Joe if it is the case.
