### ISSUE TITLE
Add new warn in xml file

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#443]
Found new warning from test kernel testing, Ubuntu 16.04

WARNING Daemon VM is provisioned, but the VM unique identifier has changed -- clearing cached state

Please add this to VERIFY-BOOT-ERROR-WARNINGS test xml file.

**Comment by LiliDeng** [comment]
@Tong-Xu Please repro it firstly.

**Comment by juhlee-microsoft** [comment]
FYI, this was from test kernel. If you need, take look at my work today in manual pipeline
