### ISSUE TITLE
PERF-STORAGE-4K-IO fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by ader1990** [microsoft/lisa#447]
The TC PERF-STORAGE-4K-IO fails on Ubuntu 18.04 with the following error:

Current Test Status: fio: native_fallocate call failed: No space left on device

**Comment by chvalean** [comment]
Problem might come from the disks used:

sda to sdl (L) are 1TB, sdm is 224GB?

Disk /dev/sdm: 224 GiB, 240518168576 bytes, 469762048 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x913ce696

Device     Boot Start       End   Sectors  Size Id Type
/dev/sdm1        2048 469762047 469760000  224G fd Linux raid autodetect


Disk /dev/sdn: 30 GiB, 32212254720 bytes, 62914560 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 1FED934C-2CC7-4FD3-B177-E8FDED1F5C22

Device      Start      End  Sectors  Size Type
/dev/sdn1  227328 62914526 62687199 29.9G Linux filesystem
/dev/sdn14   2048    10239     8192    4M BIOS boot
/dev/sdn15  10240   227327   217088  106M EFI System

**Comment by chvalean** [comment]
The key factor is the use of upstream/upstream stable kernel.
Only when using upstream kernel the disks order is getting changed, so sdb which was before known as the ephemeral disk gets changed in letter.

Could not repro this with only the default image "ARMImageName = Canonical UbuntuServer 18.04-DAILY-LTS latest" 3 out of 3 attempts. This is with the distro kernel.

**Comment by chvalean** [comment]
Code to be changed is here - https://github.com/LIS/LISAv2/blob/1b4d991e69ae04ca640f4996a4246b101f078665/Testscripts/Linux/perf_fio.sh#L151

As we can no longer rely on the fact that sdb is the ephemeral one, it can be any of the sd devices letter.
