### ISSUE TITLE
CustomKernelInstall: skip if kernel is already installed

### ISSUE THREAD

**Issue by DivyaJyothiKasam** [microsoft/lisa#453]
Testcase CAPTURE-VHD-BEFORE-TEST fails in installation of custom kernel, if the kernel passed as parameter(-CustomKernel) is already installed  in the VM.
This need to be modified to skip if kernel is already installed and CAPTURE-VHD-BEFORE-TEST should be Passed.

07/17/2019 10:48:53 : [ERROR] Kernel upgrade failed in 1 VMs.
07/17/2019 10:48:53 : [ERROR] Custom Kernel: https://lisbuildstorage04.blob.core.windows.net/kernel/3.10.0-957.21.3.el7/kernel-3.10.0-957.21.3.el7.x86_64.rpm installation FAIL. Aborting tests.

build-CustomKernel Logs:
Web link detected. Downloading https://lisbuildstorage04.blob.core.windows.net/kernel/3.10.0-957.21.3.el7/kernel-3.10.0-957.21.3.el7.x86_64.rpm
Custom Kernel:kernel-3.10.0-957.21.3.el7.x86_64.rpm
Removing packages that do not allow the kernel to be installed
Installing kernel-3.10.0-957.21.3.el7.x86_64.rpm
warning: kernel-3.10.0-957.21.3.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID fd431d51: NOKEY
Preparing...                          ########################################
	package kernel-3.10.0-957.21.3.el7.x86_64 is already installed

**Comment by chvalean** [comment]
If you skip that step then it might not be very clear that it's the same kernel.
And if it's already the same kernel, then you might want to either stop or do something else, and not just continue.
Otherwise, if you mean as in Skip state, then that is not very transparent on what it is.

**Comment by iamshital** [comment]
@DivyaJyothiKasam , can you check if you can get kernel version from rpm package version before going for install?
Based on this, we can either continue installing the kernel or skip it.

**Comment by ader1990** [comment]
This behaviour is there by design.

Also, the kernel version can be the same, but from different builds.

To "improve" or fix your scenario, you need to make sure it does make sense for all the other scenarios where you actually want to fail the test case.

In other words, why do you try to run tests with a custom kernel when you already have that kernel in the image? From a higher-level view, this scenario should not exist in your testing setup.
