### ISSUE TITLE
CreateServicePrincipal.ps1 broken in privilege assignement

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#467]
This utility script can not handle the error as expected. I have new Sub and wanted to generate new secret file.

What kind of privileges do you want to assign to the Service Principal?
1) Contributor (Default)
2) Owner
Please choose by entering 1 or 2:
1
Assign roles to Service Principal...
New-AzRoleAssignment : Principal dd51d834b65b48cf962ba048f64e2e84 does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.
At C:\Users\juhlee\Source\Repos\LIS\LISAv2\Utilities\CreateServicePrincipal.ps1:232 char:9
+         New-AzRoleAssignment -RoleDefinitionName "Contributor" -Appli ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzRoleAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand

**Comment by chvalean** [comment]
This is due to lack of privileges on subscription, must be Owner in order to create a SPN.

**Comment by juhlee-microsoft** [comment]
No, this is not about a matter of priv but about timing of PS cmd in the while loop. Running the script in PS cmd itself failed with the above error, but when it ran in PS ISE and step-by-step, it got the return value. I suspect on the line "$ErrorActionPreference = "Continue"" There might be a known issue when Get-AzADServicePrincipal cmd returns values. Need further investigation.
