### ISSUE TITLE
Support any name of AvailabilitySet

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#468]
Azure teams gave us different name of AvailabilitySet. Sometimes it is hard to rename it under pinning condition. Can LISAv2 support variable AvSet name?

**Comment by LiliDeng** [comment]
Could you please clarify detailed requirement? you mean specify the AVset name as parameter when run LISAv2, or generate a random name in code? Or you need run tests against existed environment with a different AVset name?

**Comment by juhlee-microsoft** [comment]
1. Introduce a new parameter, -UseExistingAV, then it will use the same named one in the existing EG. This parameter should be dependent on -UseExistingRG.
  a) If it is with -UseExistingRG, 
    1) If it is with -UseExistingAV, then it should use the existing AVSet in the specific RG.
    2) Otherwise, it will use the existing RG but it can create the default AVSet, AvailabilitySet.
  b) If it is NOT with -UseExistingRG, -UseExistingAV should not show up.

It is not about "creating a new AVSet". It means, it comes out above condition a)-1), but if there is no that named AVSet, the test run-time should be terminated. a)-1) case also has AvailabilitySet exists in the RG already.

**Comment by LiliDeng** [comment]
https://github.com/LIS/LISAv2/blob/master/Libraries/Azure.psm1#L860 will use existed AV in existed RG when run .\Run-LisaV2.ps1 with -UseExistingRG

https://github.com/LIS/LISAv2/blob/master/Libraries/Azure.psm1#L419 will make sure the AV is not deleted
