### ISSUE TITLE
Default OS vhd size reduction

### ISSUE THREAD

**Issue by santoshx** [microsoft/lisa#472]
It appears that VHDs are getting created with a default size of 30GB. Do we need 30GB? Can this be set to lower size?

RHEL distros recommend minimum 5GB of disk. Can we do with 5GB for all distros?

**Comment by lizzha** [comment]
If the VM is created from marketplace image, we cannot change its size. If the VM is created from custom VHD, we can decide the size of the VHD.

**Comment by santoshx** [comment]
Okay, it appears we already using the optimally sized VMs from marketplace. Thank you.
