### ISSUE TITLE
VERIFY-BOOT-ERROR-WARNINGS.py: fix test case

### ISSUE THREAD

**Issue by chvalean** [microsoft/lisa#488]
Test case is not running properly on redhat. Run the script directly, not through lisav2 to observe this better.

Release: 7.7 Snapshot 5 (most likely 7.6 should also have this behavior)

Issues to be fixed:
- ignore if syslog is not present (that exists only on ubuntu/debian).
[root@rhel77gen2 Linux]# python VERIFY-BOOT-ERROR-WARNINGS.py
2.7.5 (default, Jun 11 2019, 14:33:56)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
grep: /var/log/syslog: No such file or directory

- fix grep search
[root@rhel77gen2 Linux]#  grep -nw '/var/log/messages' -e 'mlx5'
[root@rhel77gen2 Linux]# grep /var/log/messages -e mlx5
Jul 29 10:02:27 rhel77gen2 kernel: mlx5_core ae35:00:02.0: firmware version: 14.23.1020

**Comment by LiliDeng** [comment]
@v-sijliu Please cover this

**Comment by LiliDeng** [comment]
@chvalean Could you please let know which distro you use?
