### ISSUE TITLE
Utility script CreateServicePrincipal.ps1 broken in timing

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#490]
https://github.com/LIS/LISAv2/blob/master/Utilities/CreateServicePrincipal.ps1

It shows the run-time error but passed in Admin priv Powershell ISE with debug mode. There must be something related to the timer issue.

**Comment by LiliDeng** [comment]
hi what's the failure rate when you not use ISE?

**Comment by juhlee-microsoft** [comment]
So far, 100%

**Comment by squirrelsc** [comment]
Close old threads.
