### ISSUE TITLE
The source machine name in the new tag

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#497]
LISAv2 supports the 'tagging' feature. When the user ran with '-UseExistingRG', the existing tags were not updated. In order to keep updating the RG with the latest tag information, LISAv2 should update tag information when it uses 'UseExistingRG'. 

=> update the tracking tags, by appending the latest access info (user name and build hostname ONLY) 
=> also any other PS scripts under Utilities will follow this feature. Every execution time, it will add or update the tag information with the latest ones. (user name and build hostname ONLY)

**Comment by LiliDeng** [comment]
![image](https://user-images.githubusercontent.com/10083705/62514984-8b471a80-b853-11e9-8b8c-59c5d8928a63.png)

tags if run from local machine, could you please let know what tag you want to add.

**Comment by juhlee-microsoft** [comment]
'BuildMachine' tag is already implemented? Why can't I find this tag in the existing RG use case? If we use '-useExistingRG', is it updating all tags?

**Comment by juhlee-microsoft** [comment]
Updated the description of the issues above with the team's decision today.

**Comment by juhlee-microsoft** [comment]
This task moves to the internal implementation. Will close it.
