### ISSUE TITLE
HyperV: Add support for custom kernel install for generation 2 VMs

### ISSUE THREAD

**Issue by ader1990** [microsoft/lisa#53]
LISAv2 fails to modify the proper grub.cfg on efi systems, as the path is no longer /boot/grub/grub.cfg.

Depending on the distro version, that path can be:

1. RHEL - /boot/efi/rhel/grub/grub.cfg
1. SLES - /boot/efi/sles/grub/grub.cfg

Ubuntu path must be checked too.

**Comment by stefanlupsa** [comment]
Have checked for the following for default locations: 

* Ubuntu 18.04: `/boot/efi/EFI/ubuntu/grub.cfg` `/boot/grub/grub.cfg`
* CentOS 7.6: `/boot/efi/EFI/centos/grub.cfg` `/boot/grub2/grub.cfg`
* SLES 15:  `/boot/efi/EFI/BOOT/grub.cfg` `/boot/grub2/grub.cfg`
