### ISSUE TITLE
SLES_TEST_SUDOERS_VERIFICATION_SUCCESS is included in SLES15?

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#544]
The same test kept failing in SLES 15. Is it available in SLES 15 or not? If SLES 15 no longer has it, we should remove this string inclusion in the ps1 file.

**Comment by juhlee-microsoft** [comment]
}
        elseif ($global:detectedDistro -imatch "SLES") {
            **$matchstrings = @("_TEST_SUDOERS_VERIFICATION_SUCCESS","_TEST_GRUB_VERIFICATION_SUCCESS", "_TEST_REPOSITORIES_AVAILABLE")**
            # to avoid extra blank space

**Comment by LiliDeng** [comment]
Is it the same with #338?

**Comment by juhlee-microsoft** [comment]
> Is it the same with #338?

I am checking with PM

**Comment by juhlee-microsoft** [comment]
During the information exchange, all of SLES images do not have this parameter. I think we should omit in our test script.

**Comment by juhlee-microsoft** [comment]
Added a bug to SUSE. We do not know if this is a planned change or not. https://bugzilla.suse.com/show_bug.cgi?id=1150407

**Comment by LiliDeng** [comment]
Remove this check for sles in PR #665
