### ISSUE TITLE
TIMESYNC-NTP in RHEL 8.1/SLES 15 replaces with chrony

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#561]
<RHEL 8.1> 
https://access.redhat.com/solutions/4130881

ntpdate is no longer available in RHEL8 so what can be used to sync time immediately ?

Resolution
systemctl stop chronyd
chronyd -q
systemctl start chronyd

Root Cause
ntpdate is deprecated in RHEL8 and was replaced by chrony

Diagnostic Steps
yum provides *bin/ntpdate returns no packages.
Product(s) Red Hat Enterprise LinuxComponent ntpCategory TroubleshootTags configuration documentation ntp rhel troubleshooting

<SLES 15>
https://www.suse.com/documentation/sles-15/book_sle_admin/data/cha_ntp.html

"Since SUSE Linux Enterprise Server 15, chrony is the default implementation of NTP"

**Comment by squirrelsc** [comment]
Close old threads.
