### ISSUE TITLE
ETHTOOL-GET-STATISTICS failed in RHEL 6.9

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#586]
Due to below output, it failed.

[lisa@LISAv2-OneVM-juhlee1924-SY12-20190930165550-role-0 ~]$ ethtool -S eth0
no stats available

Need to confirm if this is the expected behavior.

**Comment by juhlee-microsoft** [comment]
".get_ethtool_stats = netvsc_get_ethtool_stats" callback is not implemented. The pre-condition of this test is LIS package installation. Without it, it should be 'skippped'

**Comment by juhlee-microsoft** [comment]
@LiliDeng My proposed design is adding a new function VerifyCanEthtool in utils.sh. It checks the distro and its version. If it is the case the older than RHEL 6.9 or CentOS 6.9, then it should check the latest LIS is installed. All conditions should meet for the return value 'true'. Otherwise, it will return 'false' for the test skip. I found this change applied to a few test scripts and want to put a new function call. 
Comment?

**Comment by squirrelsc** [comment]
Close old threads.
