### ISSUE TITLE
CentOS8 has new changes

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#620]
1. python is no longer default, so it had to instaill python2 first. And create a soft link in /usr/bin/python.
2. Need to make sure how to do with kdump-tools and makedumpfile dependency installation. They are not in the official repo site.
3. c.	CENTOS_TEST_REPOSITORIES_AVAILABLE & CENTOS_TEST_GRUB_VERIFICATION_SUCCESS are missing.  The meta data shows below only.

_Last metadata expiration check: 0:00:23 ago on Fri 01 Nov 2019 11:19:26 PM UTC.
repo id           repo name                       status
AppStream         CentOS-8 - AppStream            5,532
BaseOS            CentOS-8 - Base                 2,847_

**Comment by LiliDeng** [comment]
working on it
