### ISSUE TITLE
Less variable in error handling

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#681]
if ($error.Count -gt 0) {
        $exception = $error[0].Exception
        Write-LogErr "Add-VMHardDiskDrive failed to add drive on SCSI controller $exception"
        return $False
 }

Many places use those lines. $exception variable is not used in another places, so it does not need to be there. Minimize the lines like below.

if ($error.Count -gt 0) {
        Write-LogErr "Add-VMHardDiskDrive failed to add drive on SCSI controller $error[0].Exception"
        return $False
}

**Comment by squirrelsc** [comment]
We don't enhance on V2.
