### ISSUE TITLE
CustomTestParameters in TestParameters.xml doesn't work

### ISSUE THREAD

**Issue by yuxisun1217** [microsoft/lisa#704]
Hi all,

I met a problem these days:
I set <CustomTestParameters>DATA_DISK_SKU=Standard_LRS</CustomTestParameters> in TestParameters.xml and run .\Run-LisaV2.ps1 -ParametersFile .\TestParameters.xml, but the DATA_DISK_SKU=Standard_LRS parameter is not injected to the case. 
If I run .\Run-LisaV2.ps1 -CustomTestParameters DATA_DISK_SKU=Standard_LRS , this parameter can be injected to the case.
Do you have any idea why this happened? Thanks!

.\Run-LisaV2.ps1 -XMLSecretFile .\secret.xml -ParametersFile .\TestParameters.xml
```
02/10/2020 05:52:59 : [INFO ] Setting parameter: CustomTestParameters = DATA_DISK_SKU=Standard_LRS
...
02/10/2020 05:53:30 : [INFO ] Collected test: STORAGE-HOT-ADD-DISK-PARALLEL from E:\LISAv2\HB39\XML\TestCases\FunctionalTests-Storage.xml
02/10/2020 05:53:30 : [INFO ] 1 Test Cases have been collected
02/10/2020 05:53:30 : [INFO ] DATA_DISK_SKU=Premium_LRS injected to case STORAGE-HOT-ADD-DISK-PARALLEL
```

.\Run-LisaV2.ps1 -XMLSecretFile .\secret.xml -ParametersFile .\TestParameters.xml -CustomTestParameters DATA_DISK_SKU=Standard_LRS
```
02/10/2020 05:54:18 : [INFO ] Setting parameter: CustomTestParameters = DATA_DISK_SKU=Standard_LRS
...
02/10/2020 05:54:49 : [INFO ] Collected test: STORAGE-HOT-ADD-DISK-PARALLEL from E:\LISAv2\SG25\XML\TestCases\FunctionalTests-Storage.xml
02/10/2020 05:54:49 : [INFO ] 1 Test Cases have been collected
02/10/2020 05:54:49 : [INFO ] Checking custom parameters ...
02/10/2020 05:54:50 : [INFO ] Custom Parameter: DATA_DISK_SKU=Premium_LRS --> Standard_LRS
02/10/2020 05:54:50 : [INFO ] Custom parameter(s) are ready to be injected along with default parameters, if any.
02/10/2020 05:54:50 : [INFO ] DATA_DISK_SKU=Standard_LRS injected to case STORAGE-HOT-ADD-DISK-PARALLEL
```

**Comment by lizzha** [comment]
That is by design. -ParametersFile is designed to be a replacement of inputting the parameters of Run-Lisav2.ps1

**Comment by lizzha** [comment]
You may need to set: 
```
CustomTestParameters="DATA_DISK_SKU=Standard_LRS"
``` 
in TestParameter file

**Comment by yuxisun1217** [comment]
> You may need to set:
> 
> ```
> CustomTestParameters="DATA_DISK_SKU=Standard_LRS"
> ```
> 
> in TestParameter file

Hi @lizzha ,

I have this line in TestParameters.xml:
<CustomTestParameters>DATA_DISK_SKU=Standard_LRS</CustomTestParameters>
The full TestParameters.xml is here: https://github.com/yuxisun1217/temp/blob/master/TestParameters.xml
But it doesn't work...

**Comment by yuxisun1217** [comment]
And in the log:
```
02/10/2020 05:52:59 : [INFO ] Setting parameter: CustomTestParameters = DATA_DISK_SKU=Standard_LRS
...
02/10/2020 05:53:30 : [INFO ] Collected test: STORAGE-HOT-ADD-DISK-PARALLEL from E:\LISAv2\HB39\XML\TestCases\FunctionalTests-Storage.xml
02/10/2020 05:53:30 : [INFO ] 1 Test Cases have been collected
02/10/2020 05:53:30 : [INFO ] DATA_DISK_SKU=Premium_LRS injected to case STORAGE-HOT-ADD-DISK-PARALLEL
```
Seems the CustomTestParameters = DATA_DISK_SKU=Standard_LRS is set at the very beginning, but then it is not injected in the STORAGE-HOT-ADD-DISK-PARALLEL case. I don't know why this happened...

**Comment by yuxisun1217** [comment]
This is the full log: https://github.com/yuxisun1217/temp/blob/master/LISAv2-Test-XR54.log

Thanks!
