### ISSUE TITLE
LISAv2 to support running a test with multiple VM sizes (OverrideVMSize accepts multiple values)

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#73]
Some tests are naming like <TC_name-VMSize>. A single test clones to multiple because of VM sizes.

**Suggestion:** Keep the single test case in the repo but add a new param, 'AllowedVMSize' in TC xml file. This variable is an array of supported VM sizes, so that the framework can filter out if this run-time is correct or not, depending on the result of AllowedVMSize filtering. This param is optional.

AllowedVMSize=DS15_v2,HB60rs,L80_v2, for example.

First, the framework based change is required. And then individual test cases are updated.

**Comment by LiliDeng** [comment]
let me know if my understanding is incorrect, if current size is in AllowedVMSize which contains in test case definition, then this case can continue, otherwise will mark it skip? if not specified this AllowedVMSize in xml file section, it means this case is not limited in special size?
