### ISSUE TITLE
LINUX-TEST-PROJECT-TESTS test failed all but the master result shows 'passed'

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#732]
[LISAv2 Test Results Summary]
Test Run On           : 03/24/2020 19:08:57
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
Initial Kernel Version: 5.0.0-1032-azure
Final Kernel Version  : 5.0.0-1032-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:58

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 LTP                  LINUX-TEST-PROJECT-TESTS                                                          PASS                54.73 
	proc01 : FAIL 
	quota_remount_test01 : FAIL 
	binfmt_misc02 : FAIL

**Comment by squirrelsc** [comment]
Close old threads.
