### ISSUE TITLE
UseExistingRG param shall support even if no LoadBalancer exists

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#78]
Sometimes LoadBalancer does not exist in RG, so it blocks automation run-time with '-UseExistingRG'. Suggest to create a new LoadBalancer if none is there.

**Comment by LiliDeng** [comment]
Current if no LB exists, -UseExistingRG will create one. Could you please clarify the detailed requirement? When using -UseExistingRG, what resources already in existed RG? What resources need create?

**Comment by juhlee-microsoft** [comment]
Case 1.
 1) They need the subscription id, Availability Set name and Resource Group name. No VM exists.
Case 2.
 2) if no LoadBalancer, it should be created and assign public IP to each VM.
