### ISSUE TITLE
Please consider to keep /var/log/messages in case log

### ISSUE THREAD

**Issue by yuxisun1217** [microsoft/lisa#781]
Hi there,

Can we consider to keep /var/log/messages in each case? Or at least in VERIFY-BOOT-ERROR-WARNINGS case? Sometimes we may want to search for some messages in /var/log/messages in history result. If we can keep this file somewhere in each run it will be much convenience.

Thanks!

**Comment by LiliDeng** [comment]
@yuxisun1217 
Well, it depends on how valuable this file. I suggest only add it into VERIFY-BOOT-ERROR-WARNINGS based on below points. Let know any thoughts.
- Different distro has the different file name for global system message, we store the dmesg before and after testing, but probably it will be cut based on the ring buffer setting.
- We also need consider the size of this file.
- When test failed, we can login to the VM to do the check?

**Comment by yuxisun1217** [comment]
Hi @LiliDeng ,
Agree. I think it's OK to add it into VERIFY-BOOT-ERROR-WARNINGS. I checked the /var/log/messages file in a new created VM and it was 96K which is about 3 times as big as dmesg. Maybe it's too big to collect it in every case. 
Thanks!

**Comment by yuxisun1217** [comment]
Hi @LiliDeng ,
But I didn't see any way to collect extra files in one case. Is there any way to do that? Thanks!

**Comment by LiliDeng** [comment]
@yuxisun1217 How about logmsg?

**Comment by yuxisun1217** [comment]
@LiliDeng Do you mean write /var/log/messages into VERIFY-BOOT-ERROR-WARNINGS_summary.log, after the VERIFY-BOOT-ERROR-WARNINGS.py outputs? I think it's a little messy...But if there's no better resolution it might be a choice.
Thanks!

**Comment by yuxisun1217** [comment]
@LiliDeng Oops sorry I think I misunderstood...It seems that just copy /var/log/messages into home path and rename as ${hostname}-messages.txt is ok. I'll have a try and open a PR later.

**Comment by yuxisun1217** [comment]
Close this issue since PR has been merged.
