### ISSUE TITLE
TIME-CLOCKSOURCE update

### ISSUE THREAD

**Issue by LiliDeng** [microsoft/lisa#824]
Our current design is based on 
cat /sys/devices/system/clocksource/clocksource0/available_clocksource
hyperv_clocksource_tsc_page acpi_pm

But I saw below ones during testing, after unbind. it will switch to hyperv_clocksource not acpi_pm
/sys/devices/system/clocksource/clocksource0/available_clocksource
hyperv_clocksource_tsc_page hyperv_clocksource acpi_pm

**Comment by juhlee-microsoft** [comment]
I can not reproduce your question from a few times trials in Ubuntu 20.04 (5.4.0-1016-azure). Do you have specific distro or kernel information?

**Comment by juhlee-microsoft** [comment]
#1032 #1035
