### ISSUE TITLE
[URGENT] Can we make "Clear-AzContext" as optional?

### ISSUE THREAD

**Issue by yuxisun1217** [microsoft/lisa#826]
Hi there,
Can we make the "Clear-AzContext" as optional in RunTestCleanup() which was added in (#813)? We don't have a Service Principal and can only use MFA to login, so that we need to keep the context to run our automation. This change blocks our test...
Thank you so much!

**Comment by LiliDeng** [comment]
@yuxisun1217 Sure, let me double check, if you can't use service principal, probably we can do clear if there is an azcontext there. Thanks for your feedback.

**Comment by LiliDeng** [comment]
@yuxisun1217  I don't think it is a block for you since its error action is SilentlyContinue, what is your failure, does it say this command not exist? then you need upgrade the az module.

Clear-AzContext -Force -ErrorAction SilentlyContinue | Out-NULL

**Comment by yuxisun1217** [comment]
Hi @LiliDeng ,
It's not a command failure. Because we can only use MFA to login, we need to first login manually then keep the context there to run all the automation in this slave. So we cannot clear context after a test because we cannot login again.
Thanks!

**Comment by LiliDeng** [comment]
@harz566 Can we do some adjustment when there use service principal then do clean az context?

**Comment by harz566** [comment]
Hi @yuxisun1217,  I'm looking into the issue that you reported. please help me understand your practices to run LISAv2, are you directly configure 'XML\GlobalConfigurations.xml' to run LISAv2, and never using this parameter '-XMLSecretFile' (nor service principal), right?

**Comment by yuxisun1217** [comment]
Hi @harz566 ,
I use -XMLSecretFile parameter. But I don't use LISAv2 to login. I run Connect-AzAccount and use MFA method to login manually only once before all the test, and then keep it login all the time to run my tests.

**Comment by harz566** [comment]
@yuxisun1217  So, from your XMLSecretFile, you leave a 'SubscriptionServicePrincipalKey' which is NullOrEmpty value there in your xml, right?

**Comment by yuxisun1217** [comment]
@harz566 Yes. Actually I have no such item in my secret file. 
```
<secrets>
  <SubscriptionID>xxxxx</SubscriptionID>
  <SubscriptionName>Boris_Partner</SubscriptionName>
  <ManagementEndpoint>https://management.core.windows.net</ManagementEndpoint>
  <Environment>AzureCloud</Environment>
  <ARMStorageAccount>ExistingStorage_Standard</ARMStorageAccount>
  <!--Download needed tools from the blob-->
  <blobStorageLocation>https://yujiangsriovdisks.blob.core.windows.net/yujiang</blobStorageLocation>
  <!--VMs Credential-->
  <linuxTestUsername>azureuser</linuxTestUsername>
  <linuxTestPassword>xxxxx</linuxTestPassword>
  <!--Database info for upload results-->
  <DatabaseServer>
  </DatabaseServer>
  <DatabaseUser>
  </DatabaseUser>
  <DatabasePassword>
  </DatabasePassword>
  <DatabaseName>
  </DatabaseName>
  <RegionAndStorageAccounts>
    <eastus2>
      <StandardStorage>walaautol2</StandardStorage>
      <PremiumStorage>walaautol2pre</PremiumStorage>
    </eastus2>
    <eastus>
      <StandardStorage>walaautoeastus</StandardStorage>
      <PremiumStorage>walaautoeastuspre</PremiumStorage>
    </eastus>
  </RegionAndStorageAccounts>
</secrets>
```

**Comment by harz566** [comment]
Hi @yuxisun1217,  you are unblocked, please check the latest code from master. @LiliDeng fyi.
