### ISSUE TITLE
RHEL-8.3/7.8 SRIOV-VerifyVF-Connection.sh timeout

### ISSUE THREAD

**Issue by yuxisun1217** [microsoft/lisa#866]
Hi there,

All the cases that run the SRIOV-VerifyVF-Connection.sh(and some SRIOV cases that with ssh command in shell script) has failed since Jun.17. I run this script manually and seems it hangs at ssh to dependency vm because it asks for password. Does anyone know about that? Thanks!
Failed cases: SRIOV-VERIFY-MAX-VF-CONNECTION-MAX-VCPU,SRIOV-VERIFY-MAX-VF-CONNECTION,SRIOV-VERIFY-SINGLE-VF-CONNECTION,SRIOV-DISABLEVF-ON-GUEST,SRIOV-RELOAD-MODULE,SRIOV-DISABLE-ENABLE-PCI,SRIOV-VERIFY-SINGLE-VF-CONNECTION-MAX-VCPU,SRIOV-INTERRUPTS-CHANGE

**Comment by LiliDeng** [comment]
@yuxisun1217 Let me have a try, not sure if it is related with https://github.com/LIS/LISAv2/pull/852, did you run testing successfully after this #852 ?

**Comment by yuxisun1217** [comment]
Hi @LiliDeng ,
Thanks! I'll check that. And seems I find the root cause: there are existing public keys in my VM's authorized_keys, and there's no '\n' after the end line. The new added public key is pasted in the same line after the existing public key line.

**Comment by LiliDeng** [comment]
I see, I just run SRIOV-VERIFY-SINGLE-VF-CONNECTION against gallery image RedHat RHEL 7.8 latest, works well. Before it removed all files under /root/.ssh  https://github.com/LIS/LISAv2/pull/852/files#diff-8d78de391375a62481374cb1d15840a4L18, maybe need a fix there? And we should take care of different situations.

**Comment by yuxisun1217** [comment]
Ah thanks @LiliDeng !
I double checked my original authorized_keys file and found that there's no '\n' at the end line. That's why this issue happened. Maybe I should fix it from my side.
Thank you so much for helping debug this issue!

**Comment by yuxisun1217** [comment]
Hi @LiliDeng ,
Could it be acceptable if I add an empty line before writing publickey to authorized_keys in  Testscripts/Linux/enable_passwordless_root.sh? such as:
```
    if [ -f /root/.ssh/authorized_keys ]; then
        echo >> /root/.ssh/authorized_keys
        cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
```

**Comment by LiliDeng** [comment]
@yuxisun1217 
sure if you think it can fix your issue, and create a PR, I can test ssh key authentication from my side.

**Comment by yuxisun1217** [comment]
PR has been merged.
