### ISSUE TITLE
[ERROR] Requested VM size: Standard_xxx is not yet registered to monitor. Usage simulation skipped.

### ISSUE THREAD

**Issue by yuxisun1217** [microsoft/lisa#890]
Hi there,

I've met this problem these 2 days. When I specify "-OverrideVMSize xxx" it fails and aborts the test. I'm not 100% sure but it looks like relates to the #876 . It blocks all my nightly composes test now. Could anyone please help to have a look? Thank you so much!

```
07/07/2020 03:10:47 : [INFO ] Prepare test log structure and start testing now ...
07/07/2020 03:10:47 : [INFO ] (1/1) testing started: LSVMBUS
07/07/2020 03:10:47 : [INFO ] Deploy target machine for test if required ...
07/07/2020 03:10:48 : [INFO ] Current test setup: OneVM
07/07/2020 03:10:48 : [INFO ] Checking the subscription usage...
07/07/2020 03:10:48 : [INFO ] Estimating VM #1 usage.
07/07/2020 03:10:48 : [INFO ] Measure VM capabilities of current subscription...
07/07/2020 03:10:48 : [INFO ] Measure vCPUs, Family, and AvailableLocations for each test VM Size...
07/07/2020 03:10:50 : [ERROR] Requested VM size: Standard_DS1 is not yet registered to monitor. Usage simulation skipped.
07/07/2020 03:10:52 : [ERROR] Exception detected. Source : DeployVMs()
07/07/2020 03:10:52 : [ERROR] EXCEPTION : Cannot index into a null array.
07/07/2020 03:10:52 : [ERROR] Source : Line 201 in script .\Libraries\Azure.psm1.
07/07/2020 03:10:52 : [WARN ] VMData is empty (null). Aborting the testing.
07/07/2020 03:10:52 : [INFO ] End of testing: LSVMBUS , result: Aborted
```

My command(example):
.\Run-LisaV2.ps1 -ParametersFile .\TestParameters-rhel-8.xml -XMLSecretFile .\secret.xml -TestNames "LSVMBUS" -OverrideVMSize Standard_DS1

**Comment by LiliDeng** [comment]
hi @yuxisun1217 confirmed this issue bring in by #876 , @harz566 is looking into this.

**Comment by yuxisun1217** [comment]
Thank you so much @LiliDeng @harz566 !

**Comment by harz566** [comment]
> Thank you so much @LiliDeng @harz566 !

@yuxisun1217 This issue has been fixed by PR: https://github.com/LIS/LISAv2/pull/891, it has been merged, please let me know if you still got blocked.     Sorry for inconvenience!  Have a nice day~!

**Comment by yuxisun1217** [comment]
Thank you so much for your quick fix!! @harz566
