### ISSUE TITLE
Tool 'route' need to be checked in function GetPlatform() of utils.sh and logic of ETHTOOL-GET-SET-GRO-LRO should be improved

### ISSUE THREAD

**Issue by harz566** [microsoft/lisa#934]
ETHTOOL-GET-SET-GRO-LRO     => 

Test case updated by rhel, when testing with 'Azure' platform,  because 'route' command missing, so GetPlatform() will detect incorrectly to 'HyperV' , in that case, All test case with test distros without route command installed with FAIL,  but when HOST OS has prepared and have the latest Mellanox driver installed, so the test case ETHTOOL-GET-SET-GRO-LRO will PASS by mistake, even the code of GetPlatform() has eventually return wrong Platform (HyperV).

**Comment by LiliDeng** [comment]
This case is re-designed by #960
