### ISSUE TITLE
Test summary file is missing in the test results

### ISSUE THREAD

**Issue by johnsongeorge-w** [microsoft/lisa#938]
LISAv2 framework executes the Linux shell script and log from the script is collected in ${TestName}_summary.log
Snippet from ```RunTestScript```
``` Run-LinuxCmd -Command "bash ${Script} > ${TestName}_summary.log 2>&1"```

But this log file is not collected during ```Collect-TestLogs```

Add support for collecting ${TestName}_summary.log when Linux shell script is executed by LISAv2 framework.

**Comment by LiliDeng** [comment]
during update it, we need also update the test cases which use its own ps1 test scripts.

**Comment by johnsongeorge-w** [comment]
> during update it, we need also update the test cases which use its own ps1 test scripts.

Not mandatory. Log filename is provided by PS1 script and it can be different. In such cases, PS1 should copy it back.
As a next step, we should provide a common wrapper for PS1 to invoke the Linux test script rather directly invoking it & PS1 needs to just pass the name of the test script. This will be handled later.

**Comment by johnsongeorge-w** [comment]
@harz566 Can you please close this issue #933

**Comment by harz566** [comment]
This issue has been fixed in this PR https://github.com/LIS/LISAv2/pull/933
