### ISSUE TITLE
[QUESTION]How can I get sbinfo?

### ISSUE THREAD

**Issue by yuxisun1217** [microsoft/lisa#939]
Hi there,

My last LISAv2 job was failed because of missing Tools/sbinfo. Could anyone please kindly show me the link of downloading this tool? I googled it for a while but cannot find it.
Thank you so much!

```
07/30/2020 11:36:12 : [WARN ] sbinfo file is not found in Tools folder.
07/30/2020 11:36:13 : [ERROR] EXCEPTION: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
07/30/2020 11:36:13 : [ERROR] Source: Line 758 in script .\Libraries\TestHelpers.psm1.
07/30/2020 11:36:13 : [INFO ] LISAv2 exit code: 1
```

**Comment by LiliDeng** [comment]
@juhlee-microsoft @harz566 should we share this tool? if no, we should update the code not throw exception when some tools not exist?

**Comment by yuxisun1217** [comment]
Thanks @LiliDeng ! I temporarily workaround it by touch a fake sbinfo file. It doesn't block my CI now. 
But is it possible to doc it somewhere about where to get those tools?

**Comment by juhlee-microsoft** [comment]
@prash2611 confirmed this tool is in public. https://packages.microsoft.com/repos/azurecore/pool/main/a/azure-security/ and recommends to use 2.12.0.

**Comment by yuxisun1217** [comment]
Hi @juhlee-microsoft ,
Thank you for sharing! But is there any chance I can get the package for RHEL? Or the source code I can compile it in RHEL? Thanks again!
