### ISSUE TITLE
LISAv2 archives the LIS archive on custom LIS install => creating log archive of more than 7GB

### ISSUE THREAD

**Issue by ader1990** [microsoft/lisa#95]

**Comment by ader1990** [comment]
When running tests that require LIS install from custom source, the LIS source is put in the test result directory of each test. As one LIS source file has around 800MB and if Jenkins archives the test result, we can reach at huge amount of data being stored on the Jenkins server.

If there are 50 test cases, there will be 50*800MB = ~ 40GB stored in Jenkins.

**Comment by chvalean** [comment]
This has been observed when running DPDK suite, other cases where custom LIS install option is used might also show this behavior.

**Comment by chvalean** [comment]
Remove lis archive after the install function is done.

**Comment by ader1990** [comment]
We should remove the lis rpm tar.gz after it gets installed in this method:
https://github.com/LIS/LISAv2/blob/master/Testscripts/Linux/customLISInstall.sh
